import { IsIPAD } from "@/themes/app.constant";
import { Dimensions, Image } from "react-native";
import { scale, verticalScale } from "react-native-size-matters";
//@ts-ignore
import One from "@/assets/images/onboarding/one.png";
//@ts-ignore
import Two from "@/assets/images/onboarding/two.png";
//@ts-ignore
import Three from "@/assets/images/onboarding/three.png";

export const onBoardingSlides: onBoardingSlidesTypes[] = [
  {
    color: "#F5F5F5",
    image: (
      <Image
        source={One}
        style={{
          width: IsIPAD ? verticalScale(285) : verticalScale(320),
          height: IsIPAD ? verticalScale(345) : verticalScale(330),
        }}
      />
    ),
    secondTitle: "Effortless Inventory Tracking",
    subTitle:
      "Monitor stock levels in real-time. Easily manage items by adding, editing, or deleting them. Categorize and organize your inventory for optimal efficiency.",
  },
  {
    color: "#F5F5F5",
    image: (
      <Image
        source={Two}
        style={{
          width: IsIPAD ? scale(285) : scale(320),
          height: IsIPAD ? verticalScale(345) : verticalScale(330),
        }}
      />
    ),
    secondTitle: "Smart Sales Tracking",
    subTitle:
      "Record sales transactions, monitor sales performance in real-time, and identify top-selling items. Gain insights into your business's financial health.",
  },
  {
    color: "#F5F5F5",
    image: (
      <Image
        source={Three}
        style={{
          width: IsIPAD ? scale(285) : scale(320),
          height: IsIPAD ? verticalScale(345) : verticalScale(330),
        }}
      />
    ),
    secondTitle: "Visualize Your Success with Detailed Reports",
    subTitle:
      "Gain valuable insights into your business performance with our comprehensive reporting tools. Track sales trends, analyze customer behavior, and make data-driven decisions to optimize your inventory management.",
  },
];

// onboarding variables
export enum Side {
  LEFT,
  RIGHT,
  NONE,
}
export const MIN_LEDGE = 25;
export const { width: WIDTH, height: HEIGHT } = Dimensions.get("screen");
export const MARGIN_WIDTH = MIN_LEDGE + 50;
export const PREV = WIDTH;
export const NEXT = 0;
export const LEFT_SNAP_POINTS = [MARGIN_WIDTH, PREV];
export const RIGHT_SNAP_POINTS = [NEXT, WIDTH - MARGIN_WIDTH];

export const countries = [
  { label: "🏴‍☠️ Abkhazia", value: "Abkhazia", currency: { label: "Abkhazian Apsar", value: "Apsar" } },
  { label: "🇦🇫 Afghanistan", value: "Afghanistan", currency: { label: "Afghani (AFN)", value: "AFN" } },
  { label: "🇦🇽 Åland Islands", value: "Åland Islands", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇦🇱 Albania", value: "Albania", currency: { label: "Albanian lek (ALL)", value: "ALL" } },
  { label: "🇩🇿 Algeria", value: "Algeria", currency: { label: "Algerian dinar (DZD)", value: "DZD" } },
  { label: "🇦🇸 American Samoa", value: "American Samoa", currency: { label: "US Dollar (USD)", value: "USD" } },
  { label: "🇦🇩 Andorra", value: "Andorra", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇦🇴 Angola", value: "Angola", currency: { label: "Angolan kwanza (AOA)", value: "AOA" } },
  { label: "🇦🇮 Anguilla", value: "Anguilla", currency: { label: "East Caribbean dollar (XCD)", value: "XCD" } },
  { label: "🇦🇶 Antarctica", value: "Antarctica", currency: { label: "Australian dollar (AUD)", value: "AUD" } },
  { label: "🇦🇬 Antigua and Barbuda", value: "Antigua and Barbuda", currency: { label: "East Caribbean dollar (XCD)", value: "XCD" } },
  { label: "🇦🇷 Argentina", value: "Argentina", currency: { label: "Argentine peso (ARS)", value: "ARS" } },
  { label: "🇦🇲 Armenia", value: "Armenia", currency: { label: "Armenian dram (AMD)", value: "AMD" } },
  { label: "🇦🇼 Aruba", value: "Aruba", currency: { label: "Aruban florin (AWG)", value: "AWG" } },
  { label: "🏴‍☠️ Artsakh(Nagorno - Karabakh)", value: "Artsakh(Nagorno - Karabakh)", currency: { label: "Armenian Dram (AMD)", value: "AMD" } },
  { label: "🇦🇺 Australia", value: "Australia", currency: { label: "Australian dollar (AUD)", value: "AUD" } },
  { label: "🇦🇹 Austria", value: "Austria", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇦🇿 Azerbaijan", value: "Azerbaijan", currency: { label: "Azerbaijani manat (AZN)", value: "AZN" } },
  { label: "🇧🇸 Bahamas", value: "Bahamas", currency: { label: "Bahamian dollar (BSD)", value: "BSD" } },
  { label: "🇧🇭 Bahrain", value: "Bahrain", currency: { label: "Bahraini dinar (BHD)", value: "BHD" } },
  { label: "🇧🇩 Bangladesh", value: "Bangladesh", currency: { label: "Bangladeshi taka (BDT)", value: "BDT" } },
  { label: "🇧🇧 Barbados", value: "Barbados", currency: { label: "Barbadian dollar (BBD)", value: "BBD" } },
  { label: "🇧🇾 Belarus", value: "Belarus", currency: { label: "Belarusian ruble (BYN)", value: "BYN" } },
  { label: "🇧🇪 Belgium", value: "Belgium", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇧🇿 Belize", value: "Belize", currency: { label: "Belize dollar (BZD)", value: "BZD" } },
  { label: "🇧🇯 Benin", value: "Benin", currency: { label: "West African CFA franc (XOF)", value: "XOF" } },
  { label: "🇧🇲 Bermuda", value: "Bermuda", currency: { label: "Bermudian dollar (BMD)", value: "BMD" } },
  { label: "🇧🇹 Bhutan", value: "Bhutan", currency: { label: "Bhutanese ngultrum (BTN)", value: "BTN" } },
  { label: "🇧🇴 Bolivia", value: "Bolivia", currency: { label: "Bolivian boliviano (BOB)", value: "BOB" } },
  { label: "🇧🇶 Bonaire, Sint Eustatius and Saba", value: "Bonaire, Sint Eustatius and Saba", currency: { label: "US Dollar (USD)", value: "USD" } },
  { label: "🇧🇦 Bosnia and Herzegovina", value: "Bosnia and Herzegovina", currency: { label: "Bosnia and Herzegovina convertible mark (BAM)", value: "BAM" } },
  { label: "🇧🇼 Botswana", value: "Botswana", currency: { label: "Botswana pula (BWP)", value: "BWP" } },
  { label: "🇧🇻 Bouvet Island", value: "Bouvet Island", currency: { label: "Norwegian krone (NOK)", value: "NOK" } },
  {
    label: "🇧🇷 Brazil",
    value: "Brazil",
    currency: { label: "Brazilian Real (BRL)", value: "BRL" },
  },
  {
    label: "🇻🇬 British Virgin Islands",
    value: "British Virgin Islands",
    currency: { label: "US Dollar (USD)", value: "USD" },
  },
  { label: "🇧🇳 Brunei", value: "Brunei", currency: { label: "Brunei Dollar(BND)", value: "BND" } },
  { label: "🇧🇬 Bulgaria", value: "Bulgaria", currency: { label: "Bulgarian Lev(BGN)", value: "BGN" } },
  { label: "🇧🇬 Burkina Faso", value: "Burkina Faso", currency: { label: "West African CFA Franc (XOF)", value: "XOF" } },
  { label: "🇧🇮 Burundi", value: "Burundi", currency: { label: "Burundian Franc (BIF)", value: "BIF" } },
  { label: "🇨🇻 Cabo Verde", value: "Cabo Verde", currency: { label: "Cape Verdean Escudo (CVE)", value: "CVE" } },
  { label: "🇰🇭 Cambodia", value: "Cambodia", currency: { label: "Riel (KHR)", value: "KHR" } },
  { label: "🇨🇲 Cameroon", value: "Cameroon", currency: { label: "Central African CFA Franc (XAF)", value: "XAF" } },
  {
    label: "🇨🇦 Canada",
    value: "Canada",
    currency: { label: "Canadian Dollar (CAD)", value: "CAD" },
  },
  {
    label: " 🇰🇾 Cayman Islands",
    value: "Cayman Islands",
    currency: { label: "Cayman Dollar (KYD)", value: "KYD" },
  },
  { label: "🇨🇫 Central African Republic", value: "Central African Republic", currency: { label: "Central African CFA Franc (XAF)", value: "XAF" } },
  { label: "🇹🇩 Chad", value: "Chad", currency: { label: "Central African CFA Franc(XAF)", value: "XAF" } },
  { label: "🇨🇱 Chile", value: "Chile", currency: { label: "Chilean Peso (CLP)", value: "CLP" } },
  { label: "🇨🇳 China", value: "China", currency: { label: "Renminbi (CNY)", value: "CNY" } },
  { label: "🇨🇴 Colombia", value: "Colombia", currency: { label: "Colombian Peso (COP)", value: "COP" } },
  { label: "🇰🇲 Comoros", value: "Comoros", currency: { label: "Comorian Franc (KMF)", value: "KMF" } },
  { label: "🇨🇩 Congo(DRC)", value: "Congo(DRC)", currency: { label: "Congolese Franc (CDF)", value: "CDF" } },
  { label: "🇨🇬 Congo(Republic)", value: "Congo(Republic)", currency: { label: "Central African CFA Franc (XAF)", value: "XAF" } },
  { label: "🇨🇷 Costa Rica", value: "Costa Rica", currency: { label: "Costa Rican Colón (CRC)", value: "CRC" } },
  { label: "🇭🇷 Croatia", value: "Croatia", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇨🇰 Cook Islands", value: "Cook Islands", currency: { label: "New Zealand Dollar (NZD)", value: "NZD" } },
  { label: "🇨🇺 Cuba", value: "Cuba", currency: { label: "Cuban Peso (CUP)", value: "CUP" } },
  { label: "🇨🇩 Cyprus", value: "Cyprus", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇨🇿 Czech Republic", value: "Czech Republic", currency: { label: "Czech Koruna (CZK)", value: "CZK" } },
  { label: "🇩🇰 Denmark", value: "Denmark", currency: { label: "Danish Krone (DKK)", value: "DKK" } },
  { label: "🇩🇯 Djibouti", value: "Djibouti", currency: { label: "Djiboutian Franc (DJF)", value: "DJF" } },
  { label: "🇩🇲 Dominica", value: "Dominica", currency: { label: "East Caribbean Dollar(XCD)", value: "XCD" } },
  { label: "🇩🇴 Dominican Republic", value: "Dominican Republic", currency: { label: "Dominican Peso (DOP)", value: "DOP" } },
  { label: "🇪🇨 Ecuador", value: "Ecuador", currency: { label: "US Dollar(USD)", value: "USD" } },
  { label: "🇪🇬 Egypt", value: "Egypt", currency: { label: "Egyptian Pound (EGP)", value: "EGP" } },
  { label: "🇸🇻 El Salvador", value: "El Salvador", currency: { label: "US Dollar (USD)", value: "USD" } },
  { label: "🇬🇶 Equatorial Guinea", value: "Equatorial Guinea", currency: { label: "Central African CFA Franc (XAF)", value: "XAF" } },
  { label: "🇪🇷 Eritrea", value: "Eritrea", currency: { label: "Nakfa (ERN)", value: "ERN" } },
  { label: "🇩🇰 Estonia", value: "Estonia", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇸🇿 Eswatini", value: "Eswatini", currency: { label: "Lilangeni (SZL)", value: "SZL" } },
  { label: "🇪🇹 Ethiopia", value: "Ethiopia", currency: { label: "Birr (ETB)", value: "ETB" } },
  { label: "🇫🇰 Falkland Islands ", value: "Falkland Islands", currency: { label: "Falkland Pound (FKP)", value: "FKP" } },
  { label: "🇫🇯 Fiji", value: "Fiji", currency: { label: "Fijian Dollar (FJD)", value: "FJD" } },
  { label: "🇫🇮 Finland", value: "Finland", currency: { label: "Euro (EUR)", value: "EUR" } },
  {
    label: "🇫🇷 France",
    value: "France",
    currency: { label: "Euro (EUR)", value: "EUR" },
  },
  {
    label: "🇵🇫 French Polynesia",
    value: "French Polynesia",
    currency: { label: "CFP Franc (XPF)", value: "XPF" },
  },
  { label: "🇬🇦 Gabon", value: "Gabon", currency: { label: "Central African CFA Franc (XAF)", value: "XAF" } },
  { label: "🇬🇲 Gambia", value: "Gambia", currency: { label: "Dalasi (GMD)", value: "GMD" } },
  { label: "🇬🇪 Georgia", value: "Georgia", currency: { label: "Lari (GEL)", value: "GEL" } },
  {
    label: "🇩🇪 Germany",
    value: "Germany",
    currency: { label: "Euro (EUR)", value: "EUR" },
  },
  { label: "🇬🇭 Ghana", value: "Ghana", currency: { label: "Ghanaian Cedi (GHS)", value: "GHS" } },
  { label: "🇬🇮 Gibraltar", value: "Gibraltar", currency: { label: "Gibraltar Pound (GIP)", value: "GIP" } },
  { label: "🇬🇷 Greece", value: "Greece", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇬🇱 Greenland", value: "Greenland", currency: { label: "Danish Krone (DKK)", value: "DKK" } },
  { label: "🇬🇩 Grenada", value: "Grenada", currency: { label: "East Caribbean Dollar(XCD)", value: "XCD" } },
  { label: "🇬🇺 Guam", value: "Guam", currency: { label: "US Dollar (USD)", value: "USD" } },
  { label: "🇬🇹 Guatemala", value: "Guatemala", currency: { label: "Quetzal (GTQ)", value: "GTQ" } },
  { label: "🇬🇳 Guinea", value: "Guinea", currency: { label: "Guinean Franc (GNF)", value: "GNF" } },
  { label: "🇬🇼 Guinea - Bissau", value: "Guinea - Bissau", currency: { label: "West African CFA Franc (XOF)", value: "XOF" } },
  { label: "🇬🇾 Guyana", value: "Guyana", currency: { label: "Guyanese Dollar (GYD)", value: "GYD" } },
  { label: "🇭🇹 Haiti", value: "Haiti", currency: { label: "Gourde (HTG)", value: "HTG" } },
  { label: "🇭🇳 Honduras", value: "Honduras", currency: { label: "Lempira (HNL)", value: "HNL" } },
  { label: "🇭🇺 Hungary", value: "Hungary", currency: { label: "Forint (HUF)", value: "HUF" } },
  { label: "🇭🇰 Hong Kong", value: "Hong Kong", currency: { label: "Hong Kong Dollar (HKD)", value: "HKD" } },
  { label: "🇮🇸 Iceland", value: "Iceland", currency: { label: "Icelandic Króna (ISK)", value: "ISK" } },
  { label: "🇮🇳 India", value: "India", currency: { label: "Indian Rupee (INR)", value: "INR" } },
  { label: "🇮🇩 Indonesia", value: "Indonesia", currency: { label: "Danish Krone (DKK)", value: "DKK" } },
  { label: "🇮🇷 Iran", value: "Iran", currency: { label: "Iranian Rial (IRR)", value: "IRR" } },
  { label: "🇮🇶 Iraq", value: "Iraq", currency: { label: "Iraqi Dinar (IQD)", value: "IQD" } },
  { label: "🇮🇪 Ireland", value: "Ireland", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇮🇱 Israel", value: "Israel", currency: { label: "Shekel (ILS)", value: "ILS" } },
  { label: "🇮🇹 Italy", value: "Italy", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇯🇲 Jamaica", value: "Jamaica", currency: { label: "Jamaican Dollar (JMD)", value: "JMD" } },
  {
    label: "🇯🇵 Japan",
    value: "Japan",
    currency: { label: "Japanese Yen (JPY)", value: "JPY" },
  },
  { label: "🇯🇴 Jordan", value: "Jordan", currency: { label: "Jordanian Dinar (JOD)", value: "JOD" } },
  { label: "🇰🇿 Kazakhstan", value: "Kazakhstan", currency: { label: "Tenge (KZT)", value: "KZT" } },
  { label: "🇰🇪 Kenya", value: "Kenya", currency: { label: "Kenyan Shilling (KES)", value: "KES" } },
  { label: "🇰🇮 Kiribati", value: "Kiribati", currency: { label: "Australian Dollar (AUD)", value: "AUD" } },
  { label: "🇰🇵 Korea (North)", value: "Korea (North)", currency: { label: "North Korean Won (KPW)", value: "KPW" } },
  { label: "🇰🇷 Korea (South)", value: "Korea (South)", currency: { label: "South Korean Won (KRW)", value: "KRW" } },
  { label: "🇽🇰 Kosovo", value: "Kosovo", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇰🇼 Kuwait", value: "Kuwait", currency: { label: "Kuwaiti Dinar (KWD)", value: "KWD" } },
  { label: "🇰🇬 Kyrgyzstan", value: "Kyrgyzstan", currency: { label: "Som (KGS)", value: "KGS" } },
  { label: "🇱🇦 Laos", value: "Laos", currency: { label: "Kip (LAK)", value: "LAK" } },
  { label: "🇱🇻 Latvia", value: "Latvia", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇱🇧 Lebanon", value: "Lebanon", currency: { label: "Lebanese Pound (LBP)", value: "LBP" } },
  { label: "🇱🇸 Lesotho", value: "Lesotho", currency: { label: "Loti (LSL)", value: "LSL" } },
  { label: "🇱🇷 Liberia", value: "Liberia", currency: { label: "Liberian Dollar (LRD)", value: "LRD" } },
  { label: "🇱🇾 Libya", value: "Libya", currency: { label: "Libyan Dinar (LYD)", value: "LYD" } },
  { label: "🇱🇮 Liechtenstein", value: "Liechtenstein", currency: { label: "Swiss Franc (CHF)", value: "CHF" } },
  { label: "🇱🇹 Lithuania", value: "Lithuania", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇱🇺 Luxembourg", value: "Luxembourg", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇲🇴 Macau", value: "Macau", currency: { label: "Pataca (MOP)", value: "MOP" } },
  { label: "🇲🇬 Madagascar", value: "Madagascar", currency: { label: "Malagasy Ariary (MGA)", value: "MGA" } },
  { label: "🇲🇼 Malawi", value: "Malawi", currency: { label: "Malawian Kwacha (MWK)", value: "MWK" } },
  { label: "🇲🇾 Malaysia", value: "Malaysia", currency: { label: "Ringgit (MYR)", value: "MYR" } },
  { label: "🇲🇻 Maldives", value: "Maldives", currency: { label: "Rufiyaa (MVR)", value: "MVR" } },
  { label: "🇲🇱 Mali", value: "Mali", currency: { label: "West African CFA Franc (XOF)", value: "XOF" } },
  { label: "🇲🇹 Malta", value: "Malta", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇲🇭 Marshall Islands", value: "Marshall Islands", currency: { label: "US Dollar (USD)", value: "USD" } },
  { label: "🇲🇺 Mauritania", value: "Mauritania", currency: { label: "Ouguiya (MRU)", value: "MRU" } },
  { label: "🇲🇺 Mauritius", value: "Mauritius", currency: { label: "Mauritian Rupee (MUR)", value: "MUR" } },
  { label: "🇲🇽 Mexico", value: "Mexico", currency: { label: "Mexican Peso (MXN)", value: "MXN" } },
  { label: "🇫🇲 Micronesia", value: "Micronesia", currency: { label: "US Dollar (USD)", value: "USD" } },
  { label: "🇲🇩 Moldova", value: "Moldova", currency: { label: "Leu (MDL)", value: "MDL" } },
  { label: "🇲🇨 Monaco", value: "Monaco", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇲🇳 Mongolia", value: "Mongolia", currency: { label: "Tugrik (MNT)", value: "MNT" } },
  { label: "🇲🇪 Montenegro", value: "Montenegro", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇲🇦 Morocco", value: "Morocco", currency: { label: "Moroccan Dirham (MAD)", value: "MAD" } },
  { label: "🇲🇿 Mozambique", value: "Mozambique", currency: { label: "Mozambican Metical (MZN)", value: "MZN" } },
  { label: "🇰🇬 Myanmar", value: "Myanmar", currency: { label: "Kyat (MMK)", value: "MMK" } },
  { label: "🇳🇦 Namibia", value: "Namibia", currency: { label: "Namibian Dollar (NAD)", value: "NAD" } },
  { label: "🇳🇷 Nauru", value: "Nauru", currency: { label: "Australian Dollar (AUD)", value: "AUD" } },
  { label: "🇰🇬 Nepal", value: "Nepal", currency: { label: "Nepalese Rupee (NPR)", value: "NPR" } },
  { label: "🇳🇨 New Caledonia", value: "New Caledonia", currency: { label: "CFP Franc (XPF)", value: "XPF" } },
  { label: "🇳🇱 Netherlands", value: "Netherlands", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇳🇿 New Zealand", value: "New Zealand", currency: { label: "New Zealand Dollar (NZD)", value: "NZD" } },
  { label: "🇳🇮 Nicaragua", value: "Nicaragua", currency: { label: "Córdoba (NIO)", value: "NIO" } },
  { label: "🇳🇪 Niger", value: "Niger", currency: { label: "West African CFA Franc (XOF)", value: "XOF" } },
  {
    label: "🇳🇬 Nigeria",
    value: "Nigeria",
    currency: { label: "Naira (NGN)", value: "NGN" },
  },
  {
    label: "🇳🇺 Niue",
    value: "Niue",
    currency: { label: "New Zealand Dollar (NZD)", value: "NZD" },
  },
  { label: "🇲🇰 North Macedonia", value: "North Macedonia", currency: { label: "Denar (MKD)", value: "MKD" } },
  { label: "🏴‍☠️ Northern Cyprus", value: "Northern Cyprus", currency: { label: "Turkish Lira (TRY)", value: "TRY" } },
  { label: "🇳🇴 Norway", value: "Norway", currency: { label: "Norwegian Krone (NOK)", value: "NOK" } },
  { label: "🇴🇲 Oman", value: "Omani", currency: { label: "Omani Rial (OMR)", value: "OMR" } },
  { label: "🇵🇰 Pakistan", value: "Pakistan", currency: { label: "Pakistani Rupee (PKR)", value: "PKR" } },
  { label: "🇵🇼 Palau", value: "Palau", currency: { label: "US Dollar (USD)", value: "USD" } },
  { label: "🇵🇸 Palestine", value: "Palestine", currency: { label: "Israeli Shekel (ILS)", value: "ILS" } },
  { label: "🇵🇦 Panama", value: "Panama", currency: { label: "Balboa (PAB)", value: "PAB" } },
  { label: "🇵🇬 Papua New Guinea", value: "Papua New Guinea", currency: { label: "Kina (PGK)", value: "PGK" } },
  { label: "🇵🇾 Paraguay", value: "Paraguay", currency: { label: "Guarani (PYG)", value: "PYG" } },
  { label: "🇵🇪 Peru", value: "Peru", currency: { label: "Sol (PEN)", value: "PEN" } },
  { label: "🇵🇭 Philippines", value: "Philippines", currency: { label: "Philippine Peso (PHP)", value: "PHP" } },
  { label: "🇵🇱 Poland", value: "Poland", currency: { label: "Złoty (PLN)", value: "PLN" } },
  { label: "🇵🇹 Portugal", value: "Portugal", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇵🇷 Puerto Rico", value: "Puerto Rico", currency: { label: "US Dollar (USD)", value: "USD" } },
  { label: "🇶🇦 Qatar", value: "Qatari", currency: { label: "Qatari Riyal (QAR)", value: "QAR" } },
  { label: "🇷🇴 Romania", value: "Romania", currency: { label: "Romanian Leu (RON)", value: "RON" } },
  { label: "🇷🇺 Russia", value: "Russia", currency: { label: "Russian Ruble (RUB)", value: "RUB" } },
  { label: "🇷🇼 Rwanda", value: "Rwanda", currency: { label: "Rwandan Franc (RWF)", value: "RWF" } },
  { label: "🇰🇳 Saint Kitts and Nevis", value: "Saint Kitts and Nevis", currency: { label: "East Caribbean Dollar (XCD)", value: "XCD" } },
  { label: "🇱🇨 Saint Lucia", value: "Saint Lucia", currency: { label: "East Caribbean Dollar (XCD)", value: "XCD" } },
  { label: "🇻🇨 Saint Vincent and the Grenadines", value: "Saint Vincent and the Grenadines", currency: { label: "East Caribbean Dollar (XCD)", value: "XCD" } },
  { label: "🇼🇸 Samoa", value: "Samoa", currency: { label: "Tala (WST)", value: "WST" } },
  { label: "🇸🇲 San Marino", value: "San Marino", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇸🇹 Sao Tome and Principe", value: "Sao Tome and Principe", currency: { label: "Dobra (STN)", value: "STN" } },
  { label: "🇸🇦 Saudi Arabia", value: "Saudi Arabia", currency: { label: "Saudi Riyal (SAR)", value: "SAR" } },
  { label: "🇸🇳 Senegal", value: "Senegal", currency: { label: "West African CFA Franc (XOF)", value: "XOF" } },
  { label: "🇷🇸 Serbia", value: "Serbia", currency: { label: "Serbian Dinar (RSD)", value: "RSD" } },
  { label: "🇸🇨 Seychelles", value: "Seychelles", currency: { label: "Seychellois Rupee (SCR)", value: "SCR" } },
  { label: "🇸🇱 Sierra Leone", value: "Sierra Leone", currency: { label: "Leone (SLL)", value: "SLL" } },
  { label: "🇸🇬 Singapore", value: "Singapore", currency: { label: "Singapore Dollar (SGD)", value: "SGD" } },
  { label: "🇸🇰 Slovakia", value: "Slovakia", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇸🇮 Slovenia", value: "Slovenia", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇸🇧 Solomon Islands", value: "Solomon Islands", currency: { label: "Solomons Dollar (SBD)", value: "SBD" } },
  { label: "🇸🇴 Somalia", value: "Somalia", currency: { label: "Somali Shilling (SOS)", value: "SOS" } },
  { label: "🏴‍☠️ Somaliland", value: "Somaliland", currency: { label: "Somaliland Shilling (SLSH)", value: "SLSH" } },
  { label: "🇿🇦 South Africa", value: "South Africa", currency: { label: "Rand (ZAR)", value: "ZAR" } },
  { label: "🏴‍☠️ South Ossetia", value: "South Ossetia", currency: { label: "Russian Ruble (RUB)", value: "RUB" } },
  { label: "🇪🇸 Spain", value: "Spain", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇱🇰 Sri Lanka", value: "Sri Lanka", currency: { label: "Sri Lankan Rupee (LKR)", value: "LKR" } },
  { label: "🇸🇩 Sudan", value: "Sudan", currency: { label: "Sudanese Pound (SDG)", value: "SDG" } },
  { label: "🇸🇷 Suriname", value: "Suriname", currency: { label: "Surinamese Dollar (SRD)", value: "SRD" } },
  { label: "🇸🇪 Sweden", value: "Sweden", currency: { label: "Swedish Krona (SEK)", value: "SEK" } },
  { label: "🇨🇭 Switzerland", value: "Switzerland", currency: { label: "Swiss Franc (CHF)", value: "CHF" } },
  { label: "🇸🇾 Syria", value: "Syria", currency: { label: "Syrian Pound (SYP)", value: "SYP" } },
  { label: "🇹🇼 Taiwan(ROC)", value: "Taiwan(ROC)", currency: { label: "New Taiwan Dollar (TWD)", value: "TWD" } },
  { label: "🇹🇯 Tajikistan", value: "Tajikistan", currency: { label: "Somoni (TJS)", value: "TJS" } },
  { label: "🇹🇿 Tanzania", value: "Tanzania", currency: { label: "Tanzanian Shilling (TZS)", value: "TZS" } },
  { label: "🇹🇭 Thailand", value: "Thailand", currency: { label: "Baht (THB)", value: "THB" } },
  { label: "🇹🇬 Togo", value: "Togo", currency: { label: "West African CFA Franc (XOF)", value: "XOF" } },
  { label: "🇹🇴 Tonga", value: "Tonga", currency: { label: "Paʻanga(TOP)", value: "TOP" } },
  { label: "🇹🇹 Trinidad and Tobago", value: "Trinidad and Tobago", currency: { label: "Trinidad & Tobago Dollar (TTD)", value: "TTD" } },
  { label: "🏴‍☠️ Transnistria", value: "Transnistria", currency: { label: "Transnistrian Ruble (PRB)", value: "PRB" } },
  { label: "🇹🇳 Tunisia", value: "Tunisia", currency: { label: "Tunisian Dinar (TND)", value: "TND" } },
  { label: "🇹🇷 Turkey", value: "Turkey", currency: { label: "Turkish Lira (TRY)", value: "TRY" } },
  { label: "🇹🇲 Turkmenistan", value: "Turkmenistan", currency: { label: "Manat (TMT)", value: "TMT" } },
  { label: "🇹🇻 Tuvalu", value: "Tuvalu", currency: { label: "Australian Dollar (AUD)", value: "AUD" } },
  { label: "🇺🇬 Uganda", value: "Uganda", currency: { label: "Ugandan Shilling (UGX)", value: "UGX" } },
  { label: "🇺🇦 Ukraine", value: "Ukraine", currency: { label: "Hryvnia (UAH)", value: "UAH" } },
  { label: "🇦🇪 United Arab Emirates", value: "United Arab Emirates", currency: { label: "UAE Dirham (AED)", value: "AED" } },
  {
    label: "🇬🇧 United Kingdom",
    value: "United Kingdom",
    currency: { label: "British Pound (GBP)", value: "GBP" },
  },
  {
    label: "🇺🇸 United States",
    value: "United States",
    currency: { label: "US Dollar (USD)", value: "USD" },
  },
  { label: "🇺🇾 Uruguay", value: "Uruguay", currency: { label: "Uruguayan Peso (UYU)", value: "UYU" } },
  { label: "🇻🇮 U.S.Virgin Islands", value: "U.S.Virgin Islands", currency: { label: "US Dollar (USD)", value: "USD" } },
  { label: "🇺🇿 Uzbekistan", value: "Uzbekistan", currency: { label: "Som (UZS)", value: "UZS" } },
  { label: "🇻🇺 Vanuatu", value: "Vanuatu", currency: { label: "Vatu (VUV)", value: "VUV" } },
  { label: "🇻🇦 Vatican City", value: "Vatican City", currency: { label: "Euro (EUR)", value: "EUR" } },
  { label: "🇻🇪 Venezuela", value: "Venezuela", currency: { label: "Bolívar (VES)", value: "VES" } },
  { label: "🇻🇳 Vietnam", value: "Vietnam", currency: { label: "Dong (VND)", value: "VND" } },
  { label: "🇾🇪 Yemen", value: "Yemen", currency: { label: "Yemeni Rial (YER)", value: "YER" } },
  { label: "🇿🇲 Zambia", value: "Zambia", currency: { label: "Zambian Kwacha (ZMW)", value: "ZMW" } },
  { label: "🇿🇼 Zimbabwe", value: "Zimbabwe", currency: { label: "Dollar (ZWL)", value: "ZWL" } },
]





